name: Docker Official Images JSON Builder

on: 
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
    paths-ignore:
    - 'README.md'
    - 'LICENSE'
  release:
    types: published
  schedule:
    # 4am every Saturday
    - cron: '0 4 * * 6'

jobs:
  get-image-names:
    runs-on: ubuntu-latest
    outputs:
      image-list: ${{ steps.build-image-list.outputs.IMAGE_LIST }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: docker-library/official-images
          sparse-checkout: library/
      
      - name: Build image list
        id: build-image-list
        working-directory: ./library
        run: |
          LS=$(ls | jq -cRsa 'split("\n")[:-1]')
          echo "IMAGE_LIST=$LS" >> $GITHUB_OUTPUT
          jq . <<< "$LS"

  build-json-files:
    runs-on: ubuntu-latest
    needs: get-image-names
    strategy:
      matrix:
        docker-image: ${{ needs.get-image-names.outputs.image-list }}
    steps:
      - uses: actions/checkout@v4

      - name: Check Matrix
        run: echo ${IMAGE_NAME}
        env:
          IMAGE_NAME: ${{ matrix.docker-image }}
          